/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author void
 */
public class TelaPrincipalPerfil extends javax.swing.JPanel {

    /**
     * Creates new form TelaPrincipalPerfil
     */
    public TelaPrincipalPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTelaPerfilEditar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnTelaPerfilNotificacoes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTelaPerfilAjuda = new javax.swing.JButton();
        btnTelaPerfilVoltar = new javax.swing.JButton();
        btnTelaPerfilConfiguracoes = new javax.swing.JButton();
        btnTelaPerfilSeguranca = new javax.swing.JButton();
        btnTelaPerfilCadastroEstabelecimento = new javax.swing.JButton();
        btnTelaPerfilFaleConosco = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Fullano de tal");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 97, 15);

        btnTelaPerfilEditar.setOpaque(false);
        btnTelaPerfilEditar.setContentAreaFilled(false);
        btnTelaPerfilEditar.setBorderPainted(false);
        btnTelaPerfilEditar.setForeground(new java.awt.Color(102, 102, 102));
        btnTelaPerfilEditar.setText("Editar Perfil");
        jPanel1.add(btnTelaPerfilEditar);
        btnTelaPerfilEditar.setBounds(80, 30, 117, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/foto rosto 60x60.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 54, 53);

        btnTelaPerfilNotificacoes.setOpaque(false);
        btnTelaPerfilNotificacoes.setContentAreaFilled(false);
        //btnTelaPerfilNotificacoes.setBorderPainted(false);
        btnTelaPerfilNotificacoes.setText("    Notificações");
        btnTelaPerfilNotificacoes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilNotificacoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTelaPerfilNotificacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaPerfilNotificacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnTelaPerfilNotificacoes);
        btnTelaPerfilNotificacoes.setBounds(60, 130, 192, 32);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta volta (1).png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 80, 28, 38);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(">");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 140, 10, 15);

        btnTelaPerfilAjuda.setOpaque(false);
        btnTelaPerfilAjuda.setContentAreaFilled(false);
        //btnTelaPerfilAjuda.setBorderPainted(false);
        btnTelaPerfilAjuda.setText("    Ajuda");
        btnTelaPerfilAjuda.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilAjuda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnTelaPerfilAjuda);
        btnTelaPerfilAjuda.setBounds(60, 180, 192, 30);

        btnTelaPerfilVoltar.setOpaque(false);
        btnTelaPerfilVoltar.setContentAreaFilled(false);
        //btnTelaPerfilVoltar.setBorderPainted(false);
        btnTelaPerfilVoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnTelaPerfilVoltar.setText("    Voltar");
        btnTelaPerfilVoltar.setToolTipText("");
        btnTelaPerfilVoltar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilVoltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTelaPerfilVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnTelaPerfilVoltar);
        btnTelaPerfilVoltar.setBounds(60, 90, 190, 29);

        btnTelaPerfilConfiguracoes.setOpaque(false);
        btnTelaPerfilConfiguracoes.setContentAreaFilled(false);
        //btnTelaPerfilConfiguracoes.setBorderPainted(false);
        btnTelaPerfilConfiguracoes.setText("    Configurações");
        btnTelaPerfilConfiguracoes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnTelaPerfilConfiguracoes);
        btnTelaPerfilConfiguracoes.setBounds(60, 230, 192, 32);

        btnTelaPerfilSeguranca.setOpaque(false);
        btnTelaPerfilSeguranca.setContentAreaFilled(false);
        //btnTelaPerfilSeguranca.setBorderPainted(false);
        btnTelaPerfilSeguranca.setText("    Segurança");
        btnTelaPerfilSeguranca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilSeguranca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnTelaPerfilSeguranca);
        btnTelaPerfilSeguranca.setBounds(60, 280, 192, 30);

        btnTelaPerfilCadastroEstabelecimento.setOpaque(false);
        btnTelaPerfilCadastroEstabelecimento.setContentAreaFilled(false);
        //btnTelaPerfilCadastroEstabelecimento.setBorderPainted(false);
        btnTelaPerfilCadastroEstabelecimento.setText("    Cadastre Seu Estabelecimento");
        btnTelaPerfilCadastroEstabelecimento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilCadastroEstabelecimento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnTelaPerfilCadastroEstabelecimento);
        btnTelaPerfilCadastroEstabelecimento.setBounds(60, 330, 192, 30);

        btnTelaPerfilFaleConosco.setOpaque(false);
        btnTelaPerfilFaleConosco.setContentAreaFilled(false);
        //btnTelaPerfilFaleConosco.setBorderPainted(false);
        btnTelaPerfilFaleConosco.setText("    Fale Conosco");
        btnTelaPerfilFaleConosco.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        btnTelaPerfilFaleConosco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnTelaPerfilFaleConosco);
        btnTelaPerfilFaleConosco.setBounds(60, 370, 192, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sino.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 130, 22, 32);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajuda (1).png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 180, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/engrenagem (1).png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 230, 32, 32);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loja.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 330, 32, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/escudo.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 280, 30, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fale.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 370, 32, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText(">");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(270, 190, 10, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText(">");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(270, 240, 10, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText(">");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(270, 380, 10, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText(">");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(270, 280, 10, 15);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(246, 203, 0, 0);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jLabel26.setText("Inicío");
        jPanel11.add(jLabel26);
        jLabel26.setBounds(10, 40, 37, 15);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - lupa.png"))); // NOI18N
        jPanel11.add(jLabel27);
        jLabel27.setBounds(90, 0, 30, 30);

        jLabel29.setText("Busca");
        jPanel11.add(jLabel29);
        jLabel29.setBounds(80, 40, 42, 15);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - casa.png"))); // NOI18N
        jPanel11.add(jLabel35);
        jLabel35.setBounds(10, 0, 30, 30);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - recibo.png"))); // NOI18N
        jPanel11.add(jLabel36);
        jLabel36.setBounds(170, 0, 20, 30);

        jLabel37.setText("Pedidos");
        jPanel11.add(jLabel37);
        jLabel37.setBounds(150, 40, 57, 15);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - perfil.png"))); // NOI18N
        jPanel11.add(jLabel38);
        jLabel38.setBounds(250, 0, 30, 30);

        jLabel39.setText("Perfil");
        jPanel11.add(jLabel39);
        jLabel39.setBounds(250, 40, 37, 15);

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 450, 310, 60);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText(">");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(270, 330, 10, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaPerfilNotificacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaPerfilNotificacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTelaPerfilNotificacoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaPerfilAjuda;
    private javax.swing.JButton btnTelaPerfilCadastroEstabelecimento;
    private javax.swing.JButton btnTelaPerfilConfiguracoes;
    private javax.swing.JButton btnTelaPerfilEditar;
    private javax.swing.JButton btnTelaPerfilFaleConosco;
    private javax.swing.JButton btnTelaPerfilNotificacoes;
    private javax.swing.JButton btnTelaPerfilSeguranca;
    private javax.swing.JButton btnTelaPerfilVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    // End of variables declaration//GEN-END:variables
}
