/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Pessoa.Cliente;
import Pessoa.Endereco;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Telas.TelaCadastroDadosPessoais;
import static Telas.TelaInicial.panelTelaInicialBase;
import java.awt.BorderLayout;
import jdk.nashorn.internal.scripts.JO;
/**
 *
 * @author void
 */
public class TelaCadastroEndereco extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroEndereco
     */
    
    public TelaCadastroEndereco() {
        initComponents();
    }
    
    
    
    static int numUsr = 0;
    //Criando ArrayList
    public static ArrayList<Cliente> usu = new ArrayList<>();
    
    //Funcao que cadastra o cliente
    public static boolean AdicionarUsr(Cliente Usr){
        if(usu.add(Usr) == true){
            numUsr = numUsr + 1;
            return true;
        }
        else{
            return false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoComplemento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoRua1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoBairro = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoCEP = new javax.swing.JTextField();
        btnTelaCadastroEnderecoCadastro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoCidade = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setText("ENDEREÇO");
        add(jLabel1);
        jLabel1.setBounds(110, 10, 80, 14);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("Preencha corretamente os campus.");
        add(jLabel2);
        jLabel2.setBounds(10, 40, 210, 13);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel3.setText("Complemento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 180, 14);
        jPanel1.add(txtTelaCadastroEnderecoComplemento);
        txtTelaCadastroEnderecoComplemento.setBounds(10, 30, 250, 34);

        add(jPanel1);
        jPanel1.setBounds(10, 380, 280, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel4.setText("Rua, Travessa, Alameda");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 180, 14);
        jPanel2.add(txtTelaCadastroEnderecoRua1);
        txtTelaCadastroEnderecoRua1.setBounds(10, 30, 250, 30);

        add(jPanel2);
        jPanel2.setBounds(10, 60, 280, 70);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel5.setText("Bairro");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 10, 180, 14);
        jPanel3.add(txtTelaCadastroEnderecoBairro);
        txtTelaCadastroEnderecoBairro.setBounds(10, 30, 250, 34);

        add(jPanel3);
        jPanel3.setBounds(10, 140, 280, 70);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel6.setText("CEP");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 10, 180, 14);
        jPanel4.add(txtTelaCadastroEnderecoCEP);
        txtTelaCadastroEnderecoCEP.setBounds(10, 30, 250, 34);

        add(jPanel4);
        jPanel4.setBounds(10, 220, 280, 70);

        btnTelaCadastroEnderecoCadastro.setBackground(new java.awt.Color(255, 255, 0));
        btnTelaCadastroEnderecoCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTelaCadastroEnderecoCadastro.setText("FINALIZAR CADASTRO");
        btnTelaCadastroEnderecoCadastro.setToolTipText("");
        btnTelaCadastroEnderecoCadastro.setBorder(null);
        btnTelaCadastroEnderecoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroEnderecoCadastroActionPerformed(evt);
            }
        });
        add(btnTelaCadastroEnderecoCadastro);
        btnTelaCadastroEnderecoCadastro.setBounds(20, 460, 250, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        label7.setText("Cidade");
        jPanel5.add(label7);
        label7.setBounds(10, 10, 180, 14);
        jPanel5.add(txtTelaCadastroEnderecoCidade);
        txtTelaCadastroEnderecoCidade.setBounds(10, 30, 250, 34);

        add(jPanel5);
        jPanel5.setBounds(10, 300, 280, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaCadastroEnderecoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroEnderecoCadastroActionPerformed
        TelaLogin TelaLog = new TelaLogin();
        TelaCadastroDadosPessoais DadosPessoais = new TelaCadastroDadosPessoais();
        
        //---------------------------------------------Criando um objeto cliente e adicionando seus valores--------------------------------
        Cliente Usuario = new Cliente(DadosPessoais.txtTelaCadastroNome.getText(), DadosPessoais.txtTelaCadastroCPF.getText(), DadosPessoais.txtTelaCadastroEmail.getText(),
        DadosPessoais.txtTelaCadastroTelefone.getText(), DadosPessoais.txtTelaCadastroDadosPessoaisDataNascimento.getText(), 
        DadosPessoais.pfTelaCadastroDadosPessoaisSenha.getText());
 
        //---------------------------------------------Atribuindo um endereco ao cliente
        Endereco EnderecoCliente = new Endereco(txtTelaCadastroEnderecoRua1.getText(), txtTelaCadastroEnderecoBairro.getText(), txtTelaCadastroEnderecoCEP.getText(), txtTelaCadastroEnderecoCidade.getText());
        Usuario.setEnderecoPessoa(EnderecoCliente);
       
        //--------------------------------------------Adicionando o cliente ao "Banco"--------------------------------
        if(AdicionarUsr(Usuario) == true){
            
            JOptionPane.showMessageDialog(null, "Usuario Cadastrado com Sucesso");
            
            txtTelaCadastroEnderecoBairro.setText("");
            txtTelaCadastroEnderecoCEP.setText("");
            txtTelaCadastroEnderecoCidade.setText("");
            txtTelaCadastroEnderecoComplemento.setText("");
            txtTelaCadastroEnderecoRua1.setText("");
            
           JOptionPane.showMessageDialog(null, usu.get(0).getEmail() + "" + usu.get(0).getSenha());
            JOptionPane.showMessageDialog(null, "Indo para a area de login");
            
            TelaLog.setSize(310, 510);
            TelaLog.setLocation(0, 0);


            panelTelaInicialBase.removeAll();
            panelTelaInicialBase.add(TelaLog, BorderLayout.CENTER);
            panelTelaInicialBase.revalidate();
            panelTelaInicialBase.repaint();
            numUsr = numUsr + 1;
        }else{
            JOptionPane.showMessageDialog(null, "Houveram erros no cadastro");
            txtTelaCadastroEnderecoBairro.setText("");
            txtTelaCadastroEnderecoCEP.setText("");
            txtTelaCadastroEnderecoCidade.setText("");
            txtTelaCadastroEnderecoComplemento.setText("");
            txtTelaCadastroEnderecoRua1.setText("");
        }
        
    }//GEN-LAST:event_btnTelaCadastroEnderecoCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaCadastroEnderecoCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label7;
    private javax.swing.JTextField txtTelaCadastroEnderecoBairro;
    private javax.swing.JTextField txtTelaCadastroEnderecoCEP;
    private javax.swing.JTextField txtTelaCadastroEnderecoCidade;
    private javax.swing.JTextField txtTelaCadastroEnderecoComplemento;
    private javax.swing.JTextField txtTelaCadastroEnderecoRua1;
    // End of variables declaration//GEN-END:variables
}
