/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import static Telas.TelaInicial.panelTelaInicialBase;
import java.awt.BorderLayout;

/**
 *
 * @author void
 */
public class TelaProdutos extends javax.swing.JPanel {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(310, 510));
        setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel2.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loja baiano.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 0, 60, 70);

        jLabel5.setText("Bar do Baino");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 10, 90, 15);

        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("4,7");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(80, 30, 30, 15);

        jLabel7.setText("Castanhal - 3.3km");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 30, 140, 15);

        jLabel20.setText("5 - 15 min");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(80, 50, 70, 15);

        jLabel21.setText("-  R$8,90");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(150, 50, 80, 15);

        add(jPanel2);
        jPanel2.setBounds(0, 73, 334, 82);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/seta volta - branca.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 30, 26);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Voltar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 20, 43, 15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - perfil 2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 0, 60, 60);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 334, 67);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);

        jLabel26.setText("Inicío");
        jPanel11.add(jLabel26);
        jLabel26.setBounds(10, 40, 37, 15);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - lupa.png"))); // NOI18N
        jPanel11.add(jLabel27);
        jLabel27.setBounds(90, 0, 30, 30);

        jLabel29.setText("Busca");
        jPanel11.add(jLabel29);
        jLabel29.setBounds(80, 40, 42, 15);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - casa.png"))); // NOI18N
        jPanel11.add(jLabel35);
        jLabel35.setBounds(10, 0, 30, 30);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - recibo.png"))); // NOI18N
        jPanel11.add(jLabel36);
        jLabel36.setBounds(180, 0, 20, 30);

        jLabel37.setText("Pedidos");
        jPanel11.add(jLabel37);
        jLabel37.setBounds(160, 40, 57, 15);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - perfil.png"))); // NOI18N
        jPanel11.add(jLabel38);
        jLabel38.setBounds(250, 0, 30, 30);

        jLabel39.setText("Perfil");
        jPanel11.add(jLabel39);
        jLabel39.setBounds(250, 40, 37, 15);

        add(jPanel11);
        jPanel11.setBounds(0, 450, 310, 60);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("BUDWEISER");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 0, 90, 15);

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel4.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("A partir de:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 0, 90, 15);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("R$ 5.99");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 20, 70, 17);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 100, 140, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones -cerveja.png"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 30, 40, 70);

        jLabel28.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Garrafa 1L");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(30, 10, 60, 13);

        jPanel12.add(jPanel3);
        jPanel3.setBounds(12, 12, 140, 139);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("HEINEKEN");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 0, 70, 14);

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel6.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("A partir de:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(20, 0, 90, 15);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("R$ 5.99");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(30, 20, 70, 17);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 100, 140, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones -cerveja 2.png"))); // NOI18N
        jPanel5.add(jLabel15);
        jLabel15.setBounds(60, 30, 20, 70);

        jLabel30.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Garrafa 1L");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(30, 10, 60, 13);

        jPanel12.add(jPanel5);
        jPanel5.setBounds(160, 10, 140, 139);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel9.setLayout(null);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Red Label");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(30, 0, 70, 15);

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel10.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("A partir de:");
        jPanel10.add(jLabel23);
        jLabel23.setBounds(20, 0, 90, 15);

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("R$ 84.90");
        jPanel10.add(jLabel24);
        jLabel24.setBounds(30, 20, 70, 17);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 100, 140, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - destilado.png"))); // NOI18N
        jPanel9.add(jLabel25);
        jLabel25.setBounds(50, 30, 30, 66);

        jLabel32.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Garrafa 1L");
        jPanel9.add(jLabel32);
        jLabel32.setBounds(30, 10, 59, 15);

        jPanel12.add(jPanel9);
        jPanel9.setBounds(160, 160, 140, 139);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel7.setLayout(null);

        jLabel16.setText("ÁGUA CRISTAL");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(20, 0, 100, 15);

        jPanel8.setBackground(new java.awt.Color(255, 153, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 51, 51)));
        jPanel8.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("A partir de:");
        jPanel8.add(jLabel17);
        jLabel17.setBounds(20, 0, 90, 15);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("R$ 2.59");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(30, 20, 70, 17);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 100, 140, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icones - agua mineral.png"))); // NOI18N
        jPanel7.add(jLabel19);
        jLabel19.setBounds(60, 30, 20, 66);

        jLabel31.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("500ml");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(40, 10, 59, 15);

        jPanel12.add(jPanel7);
        jPanel7.setBounds(10, 160, 140, 140);

        jScrollPane2.setViewportView(jPanel12);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 160, 340, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        TelaLojaOpcoes LojaOpcoes = new TelaLojaOpcoes();
        
        LojaOpcoes.setSize(310, 510);
        LojaOpcoes.setLocation(0, 0);
        
        
        panelTelaInicialBase.removeAll();
        panelTelaInicialBase.add(LojaOpcoes, BorderLayout.CENTER);
        panelTelaInicialBase.revalidate();
        panelTelaInicialBase.repaint();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        TelaLojaOpcoes LojaOpcoes = new TelaLojaOpcoes();
        
        LojaOpcoes.setSize(310, 510);
        LojaOpcoes.setLocation(0, 0);
        
        
        panelTelaInicialBase.removeAll();
        panelTelaInicialBase.add(LojaOpcoes, BorderLayout.CENTER);
        panelTelaInicialBase.revalidate();
        panelTelaInicialBase.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
