/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.BorderLayout;

/**
 *
 * @author void
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTelaInicialBase = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnTelaInicialCadastro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnTelaInicialLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelTelaInicialBase.setPreferredSize(new java.awt.Dimension(310, 510));
        panelTelaInicialBase.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-png-100x93.png"))); // NOI18N
        panelTelaInicialBase.add(jLabel2);
        jLabel2.setBounds(40, 60, 82, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Já possui uma conta?");
        panelTelaInicialBase.add(jLabel3);
        jLabel3.setBounds(20, 400, 200, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("sua sede!");
        panelTelaInicialBase.add(jLabel4);
        jLabel4.setBounds(60, 230, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bem-vindo ao");
        panelTelaInicialBase.add(jLabel5);
        jLabel5.setBounds(140, 90, 170, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("iDrink");
        panelTelaInicialBase.add(jLabel6);
        jLabel6.setBounds(140, 110, 80, 22);

        btnTelaInicialCadastro.setBackground(new java.awt.Color(255, 255, 0));
        btnTelaInicialCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTelaInicialCadastro.setText("CRIAR UMA CONTA");
        btnTelaInicialCadastro.setToolTipText("");
        btnTelaInicialCadastro.setBorder(null);
        panelTelaInicialBase.add(btnTelaInicialCadastro);
        btnTelaInicialCadastro.setBounds(30, 300, 250, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Falta pouco pra matar");
        panelTelaInicialBase.add(jLabel7);
        jLabel7.setBounds(60, 200, 200, 20);

        btnTelaInicialLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTelaInicialLogin.setForeground(new java.awt.Color(255, 255, 0));
        btnTelaInicialLogin.setText("Entrar");
        btnTelaInicialLogin.setBorder(null);
        btnTelaInicialLogin.setOpaque(false);
        btnTelaInicialLogin.setContentAreaFilled(false);
        btnTelaInicialLogin.setBorderPainted(false);
        btnTelaInicialLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaInicialLoginActionPerformed(evt);
            }
        });
        panelTelaInicialBase.add(btnTelaInicialLogin);
        btnTelaInicialLogin.setBounds(210, 400, 60, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ImagemFundoTelaInicial.png"))); // NOI18N
        panelTelaInicialBase.add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTelaInicialBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTelaInicialBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaInicialLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialLoginActionPerformed
        //---------------Instanciando a tela de login-------------
        TelaLogin Tela = new TelaLogin();
        
        //---------------Definindo o Tamanho da tela de login e onde ela vai aparecer-------------
        Tela.setSize(310, 510); // Tamanho
        Tela.setLocation(0, 0); // Onde irar aparecer
        
        //---------------Configurando o Painel Principal para receber o novo painel--------------
        panelTelaInicialBase.removeAll();// Removendo tudo do painel principal
        panelTelaInicialBase.add(Tela, BorderLayout.CENTER); // Chamando a tela e dizendo onde vai aparecer tambem
        panelTelaInicialBase.revalidate();
        panelTelaInicialBase.repaint();
        
    }//GEN-LAST:event_btnTelaInicialLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    

    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaInicialCadastro;
    private javax.swing.JButton btnTelaInicialLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel panelTelaInicialBase;
    // End of variables declaration//GEN-END:variables
}
