/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author void
 */
public class TelaLogin extends javax.swing.JPanel {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTelaLoginEntrar = new javax.swing.JButton();
        panelTelaLoginEmail = new javax.swing.JPanel();
        txtTelaLoginEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panelTelaLoginSenha = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pfTelaLoginSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("iDrink");
        add(jLabel6);
        jLabel6.setBounds(120, 100, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bem-vindo ao");
        add(jLabel5);
        jLabel5.setBounds(120, 80, 170, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-png-100x93.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(30, 60, 80, 83);

        btnTelaLoginEntrar.setBackground(new java.awt.Color(255, 255, 0));
        btnTelaLoginEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTelaLoginEntrar.setText("ENTRAR");
        btnTelaLoginEntrar.setToolTipText("");
        btnTelaLoginEntrar.setBorder(null);
        add(btnTelaLoginEntrar);
        btnTelaLoginEntrar.setBounds(30, 310, 250, 40);

        panelTelaLoginEmail.setBackground(new java.awt.Color(255, 255, 255, 100));
        panelTelaLoginEmail.setBorder(null);
        panelTelaLoginEmail.setLayout(null);

        txtTelaLoginEmail.setBorder(null);
        panelTelaLoginEmail.add(txtTelaLoginEmail);
        txtTelaLoginEmail.setBounds(10, 20, 256, 15);

        jLabel7.setText("E-mail");
        panelTelaLoginEmail.add(jLabel7);
        jLabel7.setBounds(10, 0, 42, 15);

        add(panelTelaLoginEmail);
        panelTelaLoginEmail.setBounds(10, 180, 280, 40);

        panelTelaLoginSenha.setBackground(new java.awt.Color(255, 255, 255, 120));
        panelTelaLoginSenha.setBorder(null);

        jLabel4.setText("Senha");

        pfTelaLoginSenha.setBorder(null);

        javax.swing.GroupLayout panelTelaLoginSenhaLayout = new javax.swing.GroupLayout(panelTelaLoginSenha);
        panelTelaLoginSenha.setLayout(panelTelaLoginSenhaLayout);
        panelTelaLoginSenhaLayout.setHorizontalGroup(
            panelTelaLoginSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLoginSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTelaLoginSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(pfTelaLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTelaLoginSenhaLayout.setVerticalGroup(
            panelTelaLoginSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTelaLoginSenhaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pfTelaLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelTelaLoginSenha);
        panelTelaLoginSenha.setBounds(10, 250, 280, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FundoTelaLogin.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 310, 520);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaLoginEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelTelaLoginEmail;
    private javax.swing.JPanel panelTelaLoginSenha;
    private javax.swing.JPasswordField pfTelaLoginSenha;
    private javax.swing.JTextField txtTelaLoginEmail;
    // End of variables declaration//GEN-END:variables
}
