/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import static Telas.TelaInicial.panelTelaInicialBase;
import java.awt.BorderLayout;
import Pessoa.Cliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author void
 */
public class TelaCadastroDadosPessoais extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroDadosPessoais
     */
    public TelaCadastroDadosPessoais() {
        initComponents();
    }
 
    
    public String ConfirmandoNome;
    public String NomeCadastro;
    public String Email;
    public String CPF;
    public String Telefone;
    public String DataNascimento;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelTelaCadastroCPF = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTelaCadastroCPF = new javax.swing.JFormattedTextField();
        panelTelaCadastroEmail = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTelaCadastroEmail = new javax.swing.JTextField();
        panelTelaCadastroDataNascimento = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTelaCadastroDadosPessoaisDataNascimento = new javax.swing.JFormattedTextField();
        panelTelaCadastroTelefone = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtTelaCadastroTelefone = new javax.swing.JFormattedTextField();
        btnTelaCadastroEnderecoCadastrar = new javax.swing.JButton();
        panelTelaCadastroNome1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtTelaCadastroSenha = new javax.swing.JTextField();
        panelTelaCadastroNome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTelaCadastroNome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(310, 510));

        jLabel1.setText("CADASTRE-SE PARA CONTINUAR");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("Complete as suas informações para realizar o cadas-");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel3.setText("tro.");

        panelTelaCadastroCPF.setBackground(new java.awt.Color(255, 255, 255));
        panelTelaCadastroCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTelaCadastroCPF.setLayout(null);

        jLabel5.setText("CPF");
        panelTelaCadastroCPF.add(jLabel5);
        jLabel5.setBounds(10, 10, 50, 14);

        try {
            txtTelaCadastroCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelTelaCadastroCPF.add(txtTelaCadastroCPF);
        txtTelaCadastroCPF.setBounds(10, 25, 270, 20);

        panelTelaCadastroEmail.setBackground(new java.awt.Color(255, 255, 255));
        panelTelaCadastroEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTelaCadastroEmail.setLayout(null);

        jLabel6.setText("E-mail");
        panelTelaCadastroEmail.add(jLabel6);
        jLabel6.setBounds(10, 10, 50, 14);
        panelTelaCadastroEmail.add(txtTelaCadastroEmail);
        txtTelaCadastroEmail.setBounds(10, 25, 270, 20);

        panelTelaCadastroDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        panelTelaCadastroDataNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTelaCadastroDataNascimento.setLayout(null);

        jLabel7.setText("Data de Nascimento");
        panelTelaCadastroDataNascimento.add(jLabel7);
        jLabel7.setBounds(10, 10, 150, 14);

        try {
            txtTelaCadastroDadosPessoaisDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelTelaCadastroDataNascimento.add(txtTelaCadastroDadosPessoaisDataNascimento);
        txtTelaCadastroDadosPessoaisDataNascimento.setBounds(10, 25, 270, 20);

        panelTelaCadastroTelefone.setBackground(new java.awt.Color(255, 255, 255));
        panelTelaCadastroTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTelaCadastroTelefone.setLayout(null);

        jLabel8.setText("Telefone");
        panelTelaCadastroTelefone.add(jLabel8);
        jLabel8.setBounds(10, 10, 70, 14);

        try {
            txtTelaCadastroTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelTelaCadastroTelefone.add(txtTelaCadastroTelefone);
        txtTelaCadastroTelefone.setBounds(10, 25, 270, 20);

        btnTelaCadastroEnderecoCadastrar.setBackground(new java.awt.Color(255, 255, 0));
        btnTelaCadastroEnderecoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTelaCadastroEnderecoCadastrar.setText("CADASTRAR E CONTINUAR");
        btnTelaCadastroEnderecoCadastrar.setToolTipText("");
        btnTelaCadastroEnderecoCadastrar.setBorder(null);
        btnTelaCadastroEnderecoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroEnderecoCadastrarActionPerformed(evt);
            }
        });

        panelTelaCadastroNome1.setBackground(new java.awt.Color(255, 255, 255));
        panelTelaCadastroNome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTelaCadastroNome1.setLayout(null);

        jLabel9.setText("Senha");
        panelTelaCadastroNome1.add(jLabel9);
        jLabel9.setBounds(10, 10, 30, 14);
        panelTelaCadastroNome1.add(txtTelaCadastroSenha);
        txtTelaCadastroSenha.setBounds(10, 25, 270, 20);

        panelTelaCadastroNome.setBackground(new java.awt.Color(255, 255, 255));
        panelTelaCadastroNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelTelaCadastroNome.setLayout(null);

        jLabel4.setText("Nome");
        panelTelaCadastroNome.add(jLabel4);
        jLabel4.setBounds(10, 10, 28, 14);
        panelTelaCadastroNome.add(txtTelaCadastroNome);
        txtTelaCadastroNome.setBounds(10, 25, 270, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTelaCadastroDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTelaCadastroCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTelaCadastroTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelTelaCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(panelTelaCadastroNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnTelaCadastroEnderecoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelTelaCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTelaCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTelaCadastroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTelaCadastroCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTelaCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTelaCadastroDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTelaCadastroNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTelaCadastroEnderecoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaCadastroEnderecoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroEnderecoCadastrarActionPerformed
        //===================================CHAMANDO A TELA DE CADASTRO DE ENDERECO=========================
        TelaCadastroEndereco TelaCadastroEndereco = new TelaCadastroEndereco();
        Cliente Cadastra = new Cliente();
        
        TelaCadastroEndereco.setSize(310, 510);
        TelaCadastroEndereco.setLocation(0, 0);
        
        
        panelTelaInicialBase.removeAll();
        panelTelaInicialBase.add(TelaCadastroEndereco, BorderLayout.CENTER);
        panelTelaInicialBase.revalidate();
        panelTelaInicialBase.repaint();
        
        //==================================FIM DA CHAMADA DA TELA DE ENDERECO==============================
        
        //=================================ATRIBUINDO VALORES AS VARIAVEIS E CRIANDO O CLIENTE==============
        NomeCadastro = txtTelaCadastroNome.getText();
        Email = txtTelaCadastroEmail.getText();
        CPF = txtTelaCadastroEmail.getText();
        Telefone = txtTelaCadastroTelefone.getText();
        DataNascimento = txtTelaCadastroEmail.getText();
        
        //Já que não estamos usando banco vamos simular um com o array list
        //Ae uma coisinha sobre ArrayList, oque eu to fazendo e o seguinte: to criando uma posição no array chamado Clientes
        //Essa "POSIÇÃO" já e o objeto e ele ja pode receber todos esse parametros que eu especifiquei pelo construtor
        //Esse NEW quer dizer que to criando um novo cliente e ele ja vai possuir tudo isso dai
        
        ConfirmandoNome = NomeCadastro;
        
        
    }//GEN-LAST:event_btnTelaCadastroEnderecoCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnTelaCadastroEnderecoCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelTelaCadastroCPF;
    private javax.swing.JPanel panelTelaCadastroDataNascimento;
    private javax.swing.JPanel panelTelaCadastroEmail;
    private javax.swing.JPanel panelTelaCadastroNome;
    private javax.swing.JPanel panelTelaCadastroNome1;
    private javax.swing.JPanel panelTelaCadastroTelefone;
    public javax.swing.JFormattedTextField txtTelaCadastroCPF;
    public javax.swing.JFormattedTextField txtTelaCadastroDadosPessoaisDataNascimento;
    public javax.swing.JTextField txtTelaCadastroEmail;
    public javax.swing.JTextField txtTelaCadastroNome;
    public javax.swing.JTextField txtTelaCadastroSenha;
    public javax.swing.JFormattedTextField txtTelaCadastroTelefone;
    // End of variables declaration//GEN-END:variables
}
