/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Pessoa.Cliente;
import Pessoa.Endereco;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Telas.TelaCadastroDadosPessoais;
/**
 *
 * @author void
 */
public class TelaCadastroEndereco extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastroEndereco
     */
    
    public TelaCadastroEndereco() {
        initComponents();
    }
    int a = 0;
    ArrayList<Cliente> Clientes = new ArrayList<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoComplemento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoRua1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoBairro = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoCEP = new javax.swing.JTextField();
        btnTelaCadastroEnderecoCadastro = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        txtTelaCadastroEnderecoCidade = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setText("ENDEREÇO");
        add(jLabel1);
        jLabel1.setBounds(110, 10, 80, 15);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setText("Preencha corretamente os campus.");
        add(jLabel2);
        jLabel2.setBounds(10, 50, 210, 13);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel3.setText("Complemento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 180, 15);
        jPanel1.add(txtTelaCadastroEnderecoComplemento);
        txtTelaCadastroEnderecoComplemento.setBounds(10, 30, 250, 19);

        add(jPanel1);
        jPanel1.setBounds(10, 350, 280, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel4.setText("Rua, Travessa, Alameda");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 180, 15);
        jPanel2.add(txtTelaCadastroEnderecoRua1);
        txtTelaCadastroEnderecoRua1.setBounds(10, 30, 250, 20);

        add(jPanel2);
        jPanel2.setBounds(10, 70, 280, 60);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel5.setText("Bairro");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 10, 180, 15);
        jPanel3.add(txtTelaCadastroEnderecoBairro);
        txtTelaCadastroEnderecoBairro.setBounds(10, 30, 250, 19);

        add(jPanel3);
        jPanel3.setBounds(10, 140, 280, 60);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel6.setText("CEP");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 10, 180, 15);
        jPanel4.add(txtTelaCadastroEnderecoCEP);
        txtTelaCadastroEnderecoCEP.setBounds(10, 30, 250, 19);

        add(jPanel4);
        jPanel4.setBounds(10, 210, 280, 60);

        btnTelaCadastroEnderecoCadastro.setBackground(new java.awt.Color(255, 255, 0));
        btnTelaCadastroEnderecoCadastro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTelaCadastroEnderecoCadastro.setText("FINALIZAR CADASTRO");
        btnTelaCadastroEnderecoCadastro.setToolTipText("");
        btnTelaCadastroEnderecoCadastro.setBorder(null);
        btnTelaCadastroEnderecoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaCadastroEnderecoCadastroActionPerformed(evt);
            }
        });
        add(btnTelaCadastroEnderecoCadastro);
        btnTelaCadastroEnderecoCadastro.setBounds(20, 430, 250, 40);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        label7.setText("Cidade");
        jPanel5.add(label7);
        label7.setBounds(10, 10, 180, 15);
        jPanel5.add(txtTelaCadastroEnderecoCidade);
        txtTelaCadastroEnderecoCidade.setBounds(10, 30, 250, 19);

        add(jPanel5);
        jPanel5.setBounds(10, 280, 280, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaCadastroEnderecoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaCadastroEnderecoCadastroActionPerformed
        int Posicao = 0;
        Endereco Auxiliar = new Endereco();
        TelaCadastroDadosPessoais Array = new TelaCadastroDadosPessoais();
        
        Auxiliar.setRua(txtTelaCadastroEnderecoRua1.getText());
        Auxiliar.setBairro(txtTelaCadastroEnderecoBairro.getText());
        Auxiliar.setCEP(txtTelaCadastroEnderecoCEP.getText());
        Auxiliar.setCidade(txtTelaCadastroEnderecoCidade.getText());
        Auxiliar.setComplemento(txtTelaCadastroEnderecoComplemento.getText());
        
        Clientes.add(a, new Cliente(Array.NomeCadastro, Array.CPF, Array.Email, Array.Telefone, Array.DataNascimento));
        JOptionPane.showMessageDialog(null, Clientes.get(a).getNome());
        JOptionPane.showMessageDialog(null, Clientes.size());
        for(int i = 0; i <= Clientes.size(); i++){
            if(Clientes.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não há clientes");
            }else{
                if(Clientes.get(i) == null){
                    JOptionPane.showMessageDialog(null, "Não há clientes");
                }else{
                    Posicao = Clientes.indexOf(Clientes.get(i).getNome().equals(Array.ConfirmandoNome));
                    Clientes.get(Posicao).setEnderecoPessoa(Auxiliar);
                    JOptionPane.showMessageDialog(null, "Cliente Cadastrado com Sucesso!!!");
                }
            }
        }
        
        for(int x = 0; x <= Clientes.size(); x++){
            JOptionPane.showMessageDialog(null, "Pessoa = " + Clientes.get(x) + "Endereco da pessoa = " + Clientes.get(x).getEnderecoPessoa());
        }
        a++;
    }//GEN-LAST:event_btnTelaCadastroEnderecoCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaCadastroEnderecoCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel label7;
    private javax.swing.JTextField txtTelaCadastroEnderecoBairro;
    private javax.swing.JTextField txtTelaCadastroEnderecoCEP;
    private javax.swing.JTextField txtTelaCadastroEnderecoCidade;
    private javax.swing.JTextField txtTelaCadastroEnderecoComplemento;
    private javax.swing.JTextField txtTelaCadastroEnderecoRua1;
    // End of variables declaration//GEN-END:variables
}
