/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Pessoa.Cliente;
import static Telas.TelaInicial.panelTelaInicialBase;
import Telas.TelaCadastroEndereco;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author void
 */
public class TelaLogin extends javax.swing.JPanel {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    public TelaCadastroEndereco TelaEd = new TelaCadastroEndereco();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTelaLoginEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pfTelaLoginSenha = new javax.swing.JPasswordField();
        btnTelaLoginEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("iDrink");
        add(jLabel6);
        jLabel6.setBounds(120, 100, 80, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bem-vindo ao");
        add(jLabel5);
        jLabel5.setBounds(120, 80, 170, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-png-100x93.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(30, 60, 80, 83);

        jLabel7.setText("E-mail");
        add(jLabel7);
        jLabel7.setBounds(20, 180, 60, 14);

        txtTelaLoginEmail.setBorder(null);
        add(txtTelaLoginEmail);
        txtTelaLoginEmail.setBounds(16, 200, 260, 30);

        jLabel4.setText("Senha");
        add(jLabel4);
        jLabel4.setBounds(20, 260, 36, 14);

        pfTelaLoginSenha.setBorder(null);
        add(pfTelaLoginSenha);
        pfTelaLoginSenha.setBounds(20, 280, 260, 30);

        btnTelaLoginEntrar.setBackground(new java.awt.Color(255, 255, 0));
        btnTelaLoginEntrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTelaLoginEntrar.setText("ENTRAR");
        btnTelaLoginEntrar.setToolTipText("");
        btnTelaLoginEntrar.setBorder(null);
        btnTelaLoginEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaLoginEntrarActionPerformed(evt);
            }
        });
        add(btnTelaLoginEntrar);
        btnTelaLoginEntrar.setBounds(30, 390, 250, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FundoTelaLogin.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, -20, 310, 550);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaLoginEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaLoginEntrarActionPerformed

        int auxEmail = -1;
        int auxSenha = -1;
        int Id = 0;
        int Veri = 0;
        
        for(int i = 0; i < TelaEd.numUsr; i++){
            if(txtTelaLoginEmail.equals(TelaEd.usu.get(i).getEmail())){
                auxEmail = i;
                Id = i;
            }
        }
        
        for(int i = 0; i < TelaEd.numUsr; i++){
            if(pfTelaLoginSenha.equals(TelaEd.usu.get(i).getSenha())){
                auxSenha = auxEmail;
            }
        }
        
        for(int i = 0; i < TelaEd.usu.size(); i++){
            JOptionPane.showMessageDialog(null, TelaEd.usu.get(Id).getEmail() + "" + TelaEd.usu.get(Id).getSenha());
        
        }
        
        JOptionPane.showMessageDialog(null, txtTelaLoginEmail.getText() + "" + pfTelaLoginSenha.getText());
        
        for(int i = 0; i < TelaEd.numUsr; i++){
            if(auxEmail != -1 && auxSenha != -1){
                Id = auxEmail;
                JOptionPane.showMessageDialog(null, "Login efetuado com Sucesso!!!");
                JOptionPane.showMessageDialog(null, "Bem vindo" + TelaEd.usu.get(Id).getNome());
                
                TelaLojaOpcoes LojaOpcoes = new TelaLojaOpcoes();

                LojaOpcoes.setSize(310, 510);
                LojaOpcoes.setLocation(0, 0);


                panelTelaInicialBase.removeAll();
                panelTelaInicialBase.add(LojaOpcoes, BorderLayout.CENTER);
                panelTelaInicialBase.revalidate();
                panelTelaInicialBase.repaint();
                Veri = 1;
            }
        }
        
        if(Veri == 0){
            JOptionPane.showMessageDialog(null, "Login ou Senha não encontrados");
            txtTelaLoginEmail.setText("");
            pfTelaLoginSenha.setText("");
        }
       
    }//GEN-LAST:event_btnTelaLoginEntrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTelaLoginEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pfTelaLoginSenha;
    private javax.swing.JTextField txtTelaLoginEmail;
    // End of variables declaration//GEN-END:variables
}
